### ISSUE TITLE
Find longest self-time?

### ISSUE THREAD

**Issue by jzaefferer** [ofrobots/require-so-slow#14]
This isn't directly about this project, but might be something that other users would also need.

The trace view in Chrome has some tooling, but so far I couldn't find anything to find or highlight the wall items with the longest self-time. I'm hoping that that is a useful metric to find the worst offenders.

Googling around I found "Show heaviest stack" mentioned on https://developers.google.com/web/tools/chrome-devtools/evaluate-performance/reference but that seems to not be available here.

Maybe I'm on the wrong path anyway - do you have general recommendations for identifying problematic dependencies?

PS: Thanks for the project!

**Comment by ofrobots** [comment]
Hi! I am glad you're finding the project useful. Yeah, so the issue is the default visualization of a timeline profile is that x-axis is time. This allows one to look at when things happened temporally. I think what you're asking for is a view that sorts the events by elapsed time rather than timestamp. I am not sure if either DevTools or chrome tracing supports that. /cc @a1ph in case he has ideas.

Personally, I keep zooming into the biggest child interval at each level. Normally problematic dependencies just jump out. It also depends on what is under your control – the entire 'heaviest stack' might not necessarily be entirely under your control. For example, [request](https://npm.im/request) is expensive to load, but I don't think it is likely that child dependencies of `request` are likely to be changed by that project. As a user of `request` I can chose to use an alternative to request if the cost doesn't match the value I might be getting out of that module – that is the only thing under my control.

**Comment by a1ph** [comment]
AFAICT if you select a bunch of trace events in the trace viewer, you should be able to see the aggregated stats for them at the bottom. You can also sort them by self time. The same works in DevTools where you can open BottomUp Tree view for a selected range.

Am I missing something and you're looking for something else?

**Comment by jzaefferer** [comment]
Closing this, since its not super important and it doesn't seem to have an obvious solution
